services:
  nginx:
    image: nginx:1.27-alpine
    container_name: taskflow_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - api
    networks:
      - taskflow-net
  
  certbot:
    image: certbot/certbot
    container_name: taskflow_certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  api:
    container_name: taskflow_api
    image: ghcr.io/k3lvin-dev/taskflow-api:main
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
      - Redis__Configuration=redis:6379
    networks:
      - taskflow-net
      
  postgres:
    image: postgres:14-alpine
    container_name: taskflow_postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - taskflow-net

  redis:
    image: redis:7-alpine
    container_name: taskflow_redis
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - taskflow-net

volumes:
  postgres_data:
  redis_data:

networks:
  taskflow-net:
    driver: bridge