services:
  # --- SERVIÇOS DE PRODUÇÃO (PRD) ---
  api_prd:
    container_name: taskflow_api_prd
    image: ghcr.io/k3lvin-dev/taskflow-api:latest # Usa a tag 'latest' para produção
    restart: always
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
      - Redis__Configuration=redis_prd:6379
    networks:
      - taskflow-net-prd

  postgres_prd:
    image: postgres:14-alpine
    container_name: taskflow_postgres_prd
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data_prd:/var/lib/postgresql/data
    networks:
      - taskflow-net-prd

  redis_prd:
    image: redis:7-alpine
    container_name: taskflow_redis_prd
    restart: always
    volumes:
      - redis_data_prd:/data
    networks:
      - taskflow-net-prd

  # --- NGINX PROXY REVERSO (COMPARTILHADO) ---
  nginx:
    image: nginx:1.27-alpine
    container_name: taskflow_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/certbot/conf:/etc/letsencrypt:ro
      - ./data/certbot/www:/var/www/certbot:ro
    depends_on:
      - api_prd
    networks:
      - taskflow-net-prd
      - taskflow-net-dev

volumes:
  postgres_data_prd:
  redis_data_prd:

networks:
  taskflow-net-prd:
    driver: bridge
  taskflow-net-dev:
    driver: bridge