services:
  # --- NGINX PROXY REVERSO (SEMPRE ATIVO) ---
  nginx:
    image: nginx:1.27-alpine
    container_name: taskflow_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/certbot/conf:/etc/letsencrypt:ro
      - ./data/certbot/www:/var/www/certbot:ro
    networks:
      - taskflow-net

  # --- SERVIÇOS DE PRODUÇÃO (PRD) ---
  api_prd:
    container_name: taskflow_api_prd
    image: ghcr.io/k3lvin-dev/taskflow-api:latest
    restart: always
    profiles: ["prd"] # Ativado apenas com --profile prd
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
      - Redis__Configuration=redis_prd:6379
    networks:
      - taskflow-net

  postgres_prd:
    image: postgres:14-alpine
    container_name: taskflow_postgres_prd
    restart: always
    profiles: ["prd"]
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data_prd:/var/lib/postgresql/data
    networks:
      - taskflow-net

  redis_prd:
    image: redis:7-alpine
    container_name: taskflow_redis_prd
    restart: always
    profiles: ["prd"]
    volumes:
      - redis_data_prd:/data
    networks:
      - taskflow-net

  # --- SERVIÇOS DE DESENVOLVIMENTO (DEV) ---
  api_dev:
    container_name: taskflow_api_dev
    image: ghcr.io/k3lvin-dev/taskflow-api:dev
    restart: always
    profiles: ["dev"] # Ativado apenas com --profile dev
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
      - Redis__Configuration=redis_dev:6379
    networks:
      - taskflow-net

  postgres_dev:
    image: postgres:14-alpine
    container_name: taskflow_postgres_dev
    restart: always
    profiles: ["dev"]
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - taskflow-net

  redis_dev:
    image: redis:7-alpine
    container_name: taskflow_redis_dev
    restart: always
    profiles: ["dev"]
    volumes:
      - redis_data_dev:/data
    networks:
      - taskflow-net

volumes:
  postgres_data_prd:
  redis_data_prd:
  postgres_data_dev:
  redis_data_dev:

networks:
  taskflow-net:
    driver: bridge