# Define os serviços (contêineres) que compõem a aplicação
services:
  # Serviço do Banco de Dados PostgreSQL
  postgres:
    image: postgres:14-alpine
    container_name: taskflow_postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - taskflow-net

  # Serviço de Cache com Redis
  redis:
    image: redis:7-alpine
    container_name: taskflow_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - taskflow-net

  # Serviço da API .NET Core
  api:
    container_name: taskflow_api
    image: ghcr.io/k3lvin-dev/taskflow-api:main
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - postgres
      - redis
    environment:
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
      - Redis__Configuration=redis:6379
    networks:
      - taskflow-net
# Volumes para persistência de dados
volumes:
  postgres_data:
  redis_data:

# Rede customizada para a comunicação entre os serviços
networks:
  taskflow-net:
    driver: bridge