name: CI/CD - Deploy TaskFlow API to VPS

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: ghcr.io/k3lvin-dev/taskflow-api

jobs:
  # Job 1: Constrói a imagem Docker e envia para o GitHub Container Registry
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  # Job 2: Deploy na VPS usando runner self-hosted
  deploy:
    needs: build-and-push
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Atualizar arquivo de ambiente
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Logar no GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
          
      - name: Criar diretórios do Certbot
        run: |
          mkdir -p ./data/certbot/conf
          mkdir -p ./data/certbot/www

      - name: Criar certificado inicial Let’s Encrypt
        run: |
          #!/bin/bash
          set -e
          
          DOMAIN="app.taskflow.vps-kinghost.net"
          EMAIL="kelvingabriel70@hotmail.com"

          echo "Parando NGINX caso esteja rodando..."
          docker compose stop nginx || true

          if [ ! -f ./data/certbot/conf/live/$DOMAIN/fullchain.pem ]; then
            echo "Criando certificado inicial para $DOMAIN..."
            docker compose run --rm -p 80:80 --entrypoint "certbot" certbot \
              certonly --standalone -d $DOMAIN --email $EMAIL --agree-tos --non-interactive
          else
            echo "Certificado já existe, pulando criação."
          fi

      - name: Deploy Docker Compose
        run: |
          echo "Baixando a imagem mais recente da API..."
          docker compose pull api

          echo "Subindo todos os contêineres..."
          docker compose up -d

          echo "Limpando imagens antigas..."
          docker image prune -af

          echo "Deploy finalizado com sucesso!"
