name: CI/CD - Deploy TaskFlow API to VPS

on:
  push:
    branches: ["main", "develop"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Fazer checkout do repositório
        uses: actions/checkout@v4

      - name: Logar no GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Definir tag da imagem
        id: image_tag
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "TAG=latest" >> $GITHUB_ENV
          else
            echo "TAG=dev" >> $GITHUB_ENV
          fi

      - name: Construir e enviar imagem Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/k3lvin-dev/taskflow-api:${{ env.TAG }}

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    environment: ${{ github.ref_name == 'main' && 'production' || 'development' }}
    steps:
      - name: Fazer checkout do repositório
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Definir perfil e variáveis de ambiente
        id: deploy_vars
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "PROFILE=prd" >> $GITHUB_ENV
            echo "ENV_FILE_SECRET=${{ secrets.ENV_FILE_PRD }}" >> $GITHUB_ENV
          else
            echo "PROFILE=dev" >> $GITHUB_ENV
            echo "ENV_FILE_SECRET=${{ secrets.ENV_FILE_DEV }}" >> $GITHUB_ENV
          fi

      - name: Atualizar arquivo .env
        run: echo "${{ env.ENV_FILE_SECRET }}" > .env

      - name: Logar no GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Criar diretórios para Certbot
        run: |
          mkdir -p ./data/certbot/conf
          mkdir -p ./data/certbot/www

      - name: Parar containers existentes para liberar a porta 80
        run: |
          docker stop taskflow_nginx || true
          docker rm taskflow_nginx || true
          docker compose down --remove-orphans || true

      - name: Gerar ou renovar certificado SSL para todos os domínios
        run: |
          CERT_DOMAINS="-d app.taskflow.vps-kinghost.net -d dev.taskflow.vps-kinghost.net -d monitor.taskflow.vps-kinghost.net"

          docker run --rm \
            -p 80:80 \
            --entrypoint /bin/sh \
            -v $(pwd)/data/certbot/conf:/etc/letsencrypt \
            -v $(pwd)/data/certbot/www:/var/www/certbot \
            certbot/certbot -c "
              if [ -d /etc/letsencrypt/live/app.taskflow.vps-kinghost.net ]; then
                echo 'Certificado encontrado. Tentando renovar...'
                certbot renew;
              else
                echo 'Nenhum certificado encontrado. Gerando um novo...'
                certbot certonly --standalone $CERT_DOMAINS --email ${{ secrets.EMAIL }} --agree-tos --non-interactive;
              fi
            "

      - name: Realizar deploy com Docker Compose
        run: |
          docker compose --profile ${{ env.PROFILE }} down --remove-orphans
          docker compose --profile ${{ env.PROFILE }} pull
          docker compose --profile ${{ env.PROFILE }} up -d
          docker image prune -af
