name: CI/CD - Deploy TaskFlow API to VPS

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: ghcr.io/k3lvin-dev/taskflow-api

jobs:
  # Job 1: Constrói a imagem Docker e a envia para o registry
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  # Job 2: Faz o deploy usando o nosso runner na VPS
  deploy:
    needs: build-and-push
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Deploy to VPS
        run: |
          echo ">>> Atualizando arquivo de ambiente .env"
          echo "${{ secrets.ENV_FILE }}" > .env

          echo ">>> Logando no GitHub Container Registry"
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
          
          echo ">>> Baixando a imagem mais recente da API"
          docker compose pull api
          
          echo ">>> Recriando os contêineres com a nova imagem"
          docker compose up -d
          
          echo ">>> Limpando imagens Docker antigas"
          docker image prune -af
          
          echo ">>> Deploy finalizado com sucesso!"